### ISSUE TITLE
Supporting comments

### ISSUE THREAD

**Issue by sedrik** [alexcrichton/toml-rs#136] opened 2017-02-01 20:52 UTC
It would be great if we could somehow support comments in toml files as that would enable us to read Cargo.toml, edit it and then write it back (this would open up for a great deal of nice to have features in cargo).

I had a quick look but did not see a clear solution as to how to support in-line comments (ordinary full line comments should be easy enough). Does anyone have a good idea?

If I get some guidance I would not mind taking a stab at implementing comment support.

**Comment by alexcrichton** [comment] 2017-02-08 05:33
Thanks for the report! I think this is a dupe of https://github.com/alexcrichton/toml-rs/issues/83 so I'm going to close in favor of that.

In general this is unfortunately a pretty difficult issue to implement. I've rewritten the parser in https://github.com/alexcrichton/toml-rs/pull/137 which supports tokenization passing through whitespace/comments at the lowest layer, but that's only the absolute bare minimum needed to edit TOML values, there's probably quite a bit more needed still.

**Closed by alexcrichton** 2017-02-08 05:33 UTC
