### ISSUE TITLE
Can't deserialize a single integer

### ISSUE THREAD

**Issue by feelingnothing** [alexcrichton/toml-rs#471] opened 2022-08-06 23:33 UTC
To reproduce on last stable version:
https://play.rust-lang.org/?edition=2021&gist=d09f8e7a6390c8c110ed79d54b0efef7

**Comment by ehuss** [comment] 2022-08-08 03:13
Parsing requires a TOML document, it doesn't support individual values. Closing as a duplicate of #253.

**Closed by ehuss** 2022-08-08 03:13 UTC
