### ISSUE TITLE
Incorrect decode

### ISSUE THREAD

**Issue by tekjar** [alexcrichton/toml-rs#116] opened 2016-10-04 12:04 UTC
Hi. I'm playing with decode example  and added `channels` member to the struct and

This doesn't work

```
#[derive(Debug, RustcDecodable)]
struct Config {
    global_string: Option<String>,
    global_integer: Option<u64>,
    server: Option<ServerConfig>,
    peers: Option<Vec<PeerConfig>>,
    channels: Vec<u8>,
}
```

http://play.integer32.com/?gist=1b59aed1fff3d968b3e705a60b0d2e24

while this works,

```
#[derive(Debug, RustcDecodable)]
struct Config {
    global_string: Option<String>,
    global_integer: Option<u64>,
    channels: Vec<u8>,
    server: Option<ServerConfig>,
    peers: Option<Vec<PeerConfig>>,
}
```

http://play.integer32.com/?gist=e6758110c7793b90e8e7a6d287b87dba

Is this behaviour correct?

**Comment by alexcrichton** [comment] 2016-10-04 14:46
Oh this depends on where you want the config of `channels` to go. In the first gist the field needs to be part of the `Peer` but in the second you've noticed it needs to be placed on `Config` itself. Depending on which is the most appropriate for your application is where you'd want to put the field.

**Comment by alexcrichton** [comment] 2017-02-08 05:29
I'm going to close this as likely working as intended, but if you've got any more questions just let me know!

**Closed by alexcrichton** 2017-02-08 05:29 UTC
