### ISSUE TITLE
reading seq of mixed int/float values into field Vec<f64> fails

### ISSUE THREAD

**Issue by DrRibosome** [alexcrichton/toml-rs#112] opened 2016-09-09 01:27 UTC
Decoding a struct that contains a sequence `Vec<f64>` field fails for input that contains mixed integers / floats. Decoding a sequence of all floats works though

```
extern crate toml;
extern crate rustc_serialize;

#[derive(Debug, RustcDecodable)]
struct Config {
    coefs: Vec<f64>,
}

let bad_test = r#"
        coefs = [1, 2, 0.18530022764383866]
    "#;

let good_test =  r#"
        coefs = [1.2, 2.2, 0.18530022764383866]
    "#;

let config: Config = toml::decode_str(bad_test).unwrap(); // FAIL HERE
println!("value: {:?}", config);
```

**Comment by alexcrichton** [comment] 2016-09-09 07:32
I believe this is a limitation of TOML which requires that arrays have values all of the same type, and the first array would have a mixture of integers/floats.

**Comment by jdc2172** [comment] 2016-09-09 16:36
It seems a tad strict to not allow upgrading integers to floats

The use case for this is generated output, which might leave off the decimal when printing some floats, yielding seemingly mixed sequences

**Comment by alexcrichton** [comment] 2016-09-09 16:46
Perhaps yeah, but this is a [restriction of the TOML specification](https://github.com/toml-lang/toml#user-content-array), so perhaps this bug could be moved to that repo?

**Comment by jdc2172** [comment] 2016-09-09 17:35
not sure if this merits an entirely new issue, but apparently it also fails to parse floats for things like `1e-05` (which is of course the same as `1e-5`)

**Comment by jdc2172** [comment] 2016-09-09 17:42
although, i suppose that's not quite in the spec either, given that the exp is an int field, and int fields can't have leading 0s...

**Comment by alexcrichton** [comment] 2016-09-09 22:15
Ah yeah it may be good to reference the proposed ABNF to see if that's allowed, could just be a parser bug!

**Comment by alexcrichton** [comment] 2017-02-08 05:28
I'm going to close this as expected behavior, due to the TOML specification.

**Closed by alexcrichton** 2017-02-08 05:28 UTC
