### ISSUE TITLE
Error::InvalidMapKeyLocation when using Serde's automatic serialization

### ISSUE THREAD

**Issue by jimmycuadra** [alexcrichton/toml-rs#81] opened 2016-01-01 11:25 UTC
I have a program that uses Serde to serialize/deserialize some types using this crate's encoder/decoder and Serde's custom derive annotations. The program compiles successfully, but when I run it and execute the serialization code path, the serialization call (`my_type.serialize(&mut encoder)`) returns `Error::InvalidMapKeyLocation` ("a map cannot be at this location") with no other information. This seems like a bug in this crate since it seems like it should be able to work with any type that Serde can automatically implement traits for. How should I go about determining why this is happening? I can try to create a reduced test case if that'd be useful.

**Comment by alexcrichton** [comment] 2016-01-11 21:42
Unfortunately TOML can't encode all Rust types or structures. It does its best to map onto `#[derive]` patterns for types such as structures, but custom serialization and/or deserialization isn't always supported (as TOML isn't that extensible of a format).

I definitely agree, however, that the error can likely be improved! This error typically happens when you're doing something like emitting the key for a table and the key is something that's not a string (e.g. an integer).

**Comment by mitchmindtree** [comment] 2016-12-17 09:24
Just ran into this when implementing some undo/redo functionality in a GUI application I'm working on. I was already using toml for a simple config file so I thought I might as well also use it for serializing the undo/redo state to a nice readable file format. I did not realise that TOML could not encode all rust types/structures - would certainly appreciate a nicer error or even a description of the limitations in the `Encoder`/`encode`/`encode_str` docs.

@alexcrichton do you happen to know the specific limitations off the top of your head?

**Comment by alexcrichton** [comment] 2016-12-19 18:02
@mitchmindtree AFAIK it's:

* Tuple structs don't really have a representation in TOML
* Various hierarchies of maps/arrays/etc aren't always representable in TOML

Although not much else is coming to mind right now, I suspect these aren't the only limitations.

**Comment by alexcrichton** [comment] 2017-02-08 05:22
I'm going to close this as intended behavior, and in the serde 0.9 rewrite (https://github.com/alexcrichton/toml-rs/pull/137) I've added an explicit error for unsupported datatypes, so hopefully this'll be more clear in the future!

**Closed by alexcrichton** 2017-02-08 05:22 UTC
